# 将来的には
# [context."mode == normal"]
# のように、より詳細な設定が出来るようにする

[normal]
# 移動系
"w" = { service = "cursor_move", type = "up" }
"a" = { service = "cursor_move", type = "left" }
"s" = { service = "cursor_move", type = "down" }
"d" = { service = "cursor_move", type = "right" }
"up" = { service = "cursor_move", type = "up" }
"left" = { service = "cursor_move", type = "left" }
"down" = { service = "cursor_move", type = "down" }
"right" = { service = "cursor_move", type = "right" }
"S-w" = { service = "cursor_move", type = "up", count = 5 }
#"S-a" = { service = "cursor_move", type = "word_backward" }
"S-a" = { service = "cursor_move", type = "left", count = 5 }
"S-s" = { service = "cursor_move", type = "down", count = 5 }
#"S-d" = { service = "cursor_move", type = "word_forward" }
"S-d" = { service = "cursor_move", type = "right", count = 5 }
#"C-a" = { service = "cursor_move", type = "line_start" }
#"C-d" = { service = "cursor_move", type = "line_end" }

# 編集系
#"h h" = { service = "edit", args = "delete_line" }
#"space" = { service = "edit", args = "delete_char_forward" }

# モード切替
"j" = { service = "set_mode", args = "insert" }
"k" = [
  { service = "set_mode", args = "insert" },
  { service = "cursor_move", type = "right" },
]
#"S-j" = [
#  { service = "edit", args = "new_line_above" },
#  { service = "set_mode", args = "insert" },
#]

# Undo/Redo
"i" = { service = "edit", args = "undo" }
"S-i" = { service = "edit", args = "redo" }

# コマンド
";" = { service = "set_mode", args = "command" }
":" = { service = "open_command" }

[insert]
"escape" = { service = "set_mode", args = "normal" }
"up" = { service = "cursor_move", type = "up" }
"left" = { service = "cursor_move", type = "left" }
"down" = { service = "cursor_move", type = "down" }
"right" = { service = "cursor_move", type = "right" }

[command]
"escape" = { service = "set_mode", args = "normal" }
"left" = { service = "cursor_move", type = "left" }
"right" = { service = "cursor_move", type = "right" }
